//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int madon { get; set; }
        public int masp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<int> tongsoluong { get; set; }
        public Nullable<decimal> tonggia { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
