//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<System.DateTime> Ngaycapnhap { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> id_sp { get; set; }
        public Nullable<int> id_kh { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
