//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public int iddichvu { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public string trangthai { get; set; }
        public string tendichvu { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public Nullable<int> makh { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
