//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int masp { get; set; }
        public Nullable<int> idDanhmuc { get; set; }
        public Nullable<int> idthuvien { get; set; }
        public string tensp { get; set; }
        public string hinh { get; set; }
        public Nullable<decimal> giaban { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<int> soluongton { get; set; }
        public string mota { get; set; }
        public Nullable<int> giamgia { get; set; }
        public Nullable<decimal> giakhuyenmai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ThuVienAnh ThuVienAnh { get; set; }
    }
}
